// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconAdd: typeof import('./src/components/icons/IconAdd.vue')['default']
    ILoading: typeof import('./src/components/icons/ILoading.vue')['default']
    SButton: typeof import('./src/components/SButton.vue')['default']
    SInput: typeof import('./src/components/SInput.vue')['default']
    SSelect: typeof import('./src/components/SSelect.vue')['default']
  }
}
